In [ ]:
import zipfile
with zipfile.ZipFile('/content/drive/My Drive/NER/VLSP2018-NER-train.zip', 'r') as zipObj:
    zipObj.extractall()
with zipfile.ZipFile('/content/drive/My Drive/NER/VLSP2018-NER-dev.zip', 'r') as zipObj:
    zipObj.extractall()
with zipfile.ZipFile('/content/drive/My Drive/NER/VLSP2018-NER-Test-Domains.zip', 'r') as zipObj:
    zipObj.extractall()

In [ ]:
import re
import os

list_path=['/content/VLSP2018-NER-Test-Domains/', '/content/VLSP2018-NER-dev/',
           '/content/VLSP2018-NER-train-Jan14/']

sentences=[]
labels=[]

for file_path in list_path:
    all_folder=os.listdir(file_path)

    for folder_name in all_folder:
        file_in_folder=os.listdir(file_path+folder_name)

        for file_name in file_in_folder:
            f = open(file_path+folder_name+'/'+file_name, "r")
            s=f.read()
            s1=s.split("\n")
            s3=[]
            for s2 in s1:
                if (s2!=""):
                    s4=s2.split(". ")
                    for s5 in s4:
                        if (s5!=""):
                            s3.append(s5)
            s4=[]
            for s2 in s3:
                s4.append(re.findall(r"[\w']+", s2))

            for s2 in s4:
                if (len(s2)>500):
                    continue
                sentence=[]
                label=[]
                i=0
                while i<len(s2):
                    if (s2[i]=='ENAMEX'):
                        i+=2
                        if (i+1>=len(s2)):
                            break
                        if (s2[i]=='PERSON' or s2[i]=='LOCATION'):
                            i+=1
                            sentence.append(s2[i].lower())
                            label.append(1)
                            i+=1
                            if (i>=len(s2)):
                                break
                            while (s2[i]!='ENAMEX'):
                                sentence.append(s2[i].lower())
                                label.append(2)
                                if (i+1<len(s2)):
                                    i+=1
                                else:
                                    break
                        else:
                            i+=1
                            while (s2[i]!='ENAMEX'):
                                sentence.append(s2[i].lower())
                                label.append(0)
                                i+=1
                                if (i>=len(s2)):
                                    break
                            i+=1
                    else:
                        sentence.append(s2[i].lower())
                        label.append(0)
                    i+=1
                sentences.append(sentence)
                labels.append(label)

In [ ]:
print(sentences[3])

['tôi', 'lấy', 'chồng', 'năm', '2006', 'năm', '2008', 'chúng', 'tôi', 'có', 'mâu', 'thuẫn', 'tôi', 'và', 'con', 'đã', 'dọn', 'ra', 'khỏi', 'nhà', 'bố', 'mẹ', 'chồng', 'sống', 'ly', 'thân', 'với', 'chồng', 'từ', 'bấy', 'đến', 'giờ']


In [ ]:
print(len(sentences))

30232


In [ ]:
for i in range(len(sentences)):
    for j in range(len(sentences[i])):
        if (labels[i][j]==1):
            a=sentences[i][j]
            k=j+1
            while (k<len(sentences[i]) and labels[i][k]==2):
                a+=' '+sentences[i][k]
                k+=1
            print(a)

Kết quả truyền trực tuyến bị cắt bớt đến 5000 dòng cuối.
trump
mỹ
châu âu
mỹ
trump
merkel
mỹ
đức
trump
mỹ
merkel
trump
merkel
hillary clinton
angela merkel
mỹ
đức
bang north carolina
đức
merkel
đức
merkel
mỹ
mỹ
đức
jeremy shapiro
đức
merkel
shapiro
trump
merkel
phương thảo
idlib
thành phố idlib
abu yahya tunisi
abu soleiman maghrebi
idlib
abu dajaneh faransavi
thành phố idlib
thành phố idlib
syria
thành phố idlib
mỹ
nga
mỹ
nga
nga
washington
iran
bình nhưỡng
mỹ
rex tillerson
nga
mỹ
rex tillerson
nga
nga
nga
tillerson
mỹ
nga
moscow
washington
triều tiên
iran
triều tiên
nebenzia
nga
iran
mỹ
nga
trung quốc
pháp
anh
đức
nebenzia
mỹ
nga
anh
trung quốc
pháp
ấn độ
pakistan
triều tiên
israel
triều tiên
hàn quốc
hàn quốc
seo ok ryol
triều tiên
seo ok ryol
triều tiên
seo
miền nam
bán đảo triều tiên
seo
triều tiên
seoul
seo
triều tiên
hàn quốc
triều tiên
seo
bình nhưỡng
triều tiên
seo
seo
hàn quốc
bình nhưỡng
seo
sông yeomhwa
hàn quốc
bình nhưỡng
seoul
hàn quốc
seo
seo
seoul
hàn quốc
triều tiên
s

In [ ]:
import pandas as pd
list_word=[]
for sentence in sentences:
    list_word+=sentence
list_word=pd.DataFrame(list_word)
print(list_word)

             0
0         chưa
1           ly
2          hôn
3        chồng
4          tôi
...        ...
824214    theo
824215  nguyên
824216    thảo
824217     dân
824218    việt

[824219 rows x 1 columns]


In [ ]:
words = list(list_word[0].unique())
print(words)

['chưa', 'ly', 'hôn', 'chồng', 'tôi', 'và', 'bồ', 'tổ', 'chức', 'đám', 'cưới', 'liệu', 'có', 'phạm', 'pháp', 'vẫn', 'nhưng', 'đã', 'vợ', 'mới', 'như', 'vậy', 'vi', 'luật', 'hay', 'không', 'lấy', 'năm', '2006', '2008', 'chúng', 'mâu', 'thuẫn', 'con', 'dọn', 'ra', 'khỏi', 'nhà', 'bố', 'mẹ', 'sống', 'thân', 'với', 'từ', 'bấy', 'đến', 'giờ', 'trong', 'suốt', 'thời', 'gian', 'quan', 'hệ', 'tình', 'cảm', 'đầu', '2017', 'yêu', 'một', 'cô', 'gái', 'muốn', 'cầu', 'để', 'anh', 'đi', 'bước', 'nữa', 'chấp', 'nhận', 'ký', 'vào', 'đơn', 'cùng', 'người', 'công', 'khai', 'lại', 'ta', 'cũng', 'mật', 'thiết', 'gia', 'đình', 'khi', 'cảnh', 'cáo', 'thì', 'nói', 'rằng', 'nộp', 'tòa', 'rồi', 'cho', 'nên', 'mặc', 'định', 'thể', 'đường', 'chính', 'được', 'biết', 'họ', 'tháng', '10', 'hiện', 'nay', 'thấy', 'phía', 'án', 'thông', 'báo', 'gì', '12', 'kia', 'lễ', 'xin', 'hỏi', 'sư', 'đúng', 'kiện', 'vì', 'tội', 'nếu', 'sẽ', 'phải', 'chịu', 'trách', 'nhiệm', 'trước', 'huỳnh', 'mỹ', 'long', 'giám', 'đốc', 'ty', 'tâ

In [ ]:
word2idx = {w : i + 2 for i, w in enumerate(words)}
word2idx["UNK"] = 1
word2idx["PAD"] = 0
print(word2idx)

{'chưa': 2, 'ly': 3, 'hôn': 4, 'chồng': 5, 'tôi': 6, 'và': 7, 'bồ': 8, 'tổ': 9, 'chức': 10, 'đám': 11, 'cưới': 12, 'liệu': 13, 'có': 14, 'phạm': 15, 'pháp': 16, 'vẫn': 17, 'nhưng': 18, 'đã': 19, 'vợ': 20, 'mới': 21, 'như': 22, 'vậy': 23, 'vi': 24, 'luật': 25, 'hay': 26, 'không': 27, 'lấy': 28, 'năm': 29, '2006': 30, '2008': 31, 'chúng': 32, 'mâu': 33, 'thuẫn': 34, 'con': 35, 'dọn': 36, 'ra': 37, 'khỏi': 38, 'nhà': 39, 'bố': 40, 'mẹ': 41, 'sống': 42, 'thân': 43, 'với': 44, 'từ': 45, 'bấy': 46, 'đến': 47, 'giờ': 48, 'trong': 49, 'suốt': 50, 'thời': 51, 'gian': 52, 'quan': 53, 'hệ': 54, 'tình': 55, 'cảm': 56, 'đầu': 57, '2017': 58, 'yêu': 59, 'một': 60, 'cô': 61, 'gái': 62, 'muốn': 63, 'cầu': 64, 'để': 65, 'anh': 66, 'đi': 67, 'bước': 68, 'nữa': 69, 'chấp': 70, 'nhận': 71, 'ký': 72, 'vào': 73, 'đơn': 74, 'cùng': 75, 'người': 76, 'công': 77, 'khai': 78, 'lại': 79, 'ta': 80, 'cũng': 81, 'mật': 82, 'thiết': 83, 'gia': 84, 'đình': 85, 'khi': 86, 'cảnh': 87, 'cáo': 88, 'thì': 89, 'nói': 90, 'r

In [ ]:
idx2word = {i: w for w, i in word2idx.items()}

In [ ]:
max_len=0
for sentence in sentences:
    if (len(sentence)>max_len):
        max_len=len(sentence)
print(max_len)

223


In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

X = [[word2idx[w] for w in s] for s in sentences]
X = pad_sequences(maxlen = max_len, sequences = X, padding = "post", value = word2idx["PAD"])
y = pad_sequences(maxlen = max_len, sequences = labels, padding = "post", value = 3)

In [ ]:
print(y)

[[0 0 0 ... 3 3 3]
 [0 0 0 ... 3 3 3]
 [0 0 0 ... 3 3 3]
 ...
 [0 0 1 ... 3 3 3]
 [0 0 0 ... 3 3 3]
 [0 0 0 ... 3 3 3]]


In [ ]:
from tensorflow.keras.utils import to_categorical
y = [to_categorical(i, num_classes = 4) for i in y]
print(y)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1)

In [ ]:
import numpy as np
np.save("/content/drive/My Drive/NER/x_train.npy", X_train)
np.save("/content/drive/My Drive/NER/x_test.npy", X_test)
np.save("/content/drive/My Drive/NER/y_train.npy", y_train)
np.save("/content/drive/My Drive/NER/y_test.npy", y_test)

NameError: ignored

In [ ]:
import numpy as np
X_train=np.load("/content/drive/My Drive/NER/x_train.npy")
X_test=np.load("/content/drive/My Drive/NER/x_test.npy")
y_train=np.load("/content/drive/My Drive/NER/y_train.npy")
y_test=np.load("/content/drive/My Drive/NER/y_test.npy")

In [ ]:
pip install tf2crf

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Bidirectional, LSTM, TimeDistributed, Dense, Dropout, BatchNormalization
from tf2crf import CRF

model=Sequential()
model.add(Embedding(input_dim=len(word2idx), output_dim=40, input_length=max_len, mask_zero=False))
model.add(Bidirectional(LSTM(units=100, return_sequences=True, recurrent_dropout=0.6, dropout=0.6)))
model.add(TimeDistributed(Dense(100, activation="relu")))
model.add(Dropout(0.6))
crf = CRF(4)
model.add(crf)

model.compile(optimizer="adam", loss=crf.loss, metrics=[crf.accuracy])

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 223, 40)           533800    
_________________________________________________________________
bidirectional (Bidirectional (None, 223, 200)          112800    
_________________________________________________________________
time_distributed (TimeDistri (None, 223, 100)          20100     
_________________________________________________________________
dropout (Dropout)            (None, 223, 100)          0         
_________________________________________________________________
crf (CRF)                    (None, 223)               10000     
Total params: 676,700
Trainable params: 676,700
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.load_weights("/content/drive/My Drive/NER/model.h5")

In [ ]:
from tensorflow.keras.callbacks import ModelCheckpoint
checkpoint = ModelCheckpoint(filepath = '/content/drive/My Drive/NER/model.h5',
                        verbose = 0,
                        mode = 'auto',
                        save_best_only = True,
                        monitor='val_loss')

model.fit(np.array(X_train), np.array(y_train), batch_size=128, epochs=50, 
          validation_data=(np.array(X_test), np.array(y_test)), callbacks=[checkpoint])

Epoch 1/50
213/213 [==============================] - 830s 4s/step - loss: 3.3403 - accuracy: 0.0000e+00 - val_loss: 3.8846 - val_accuracy: 0.9976
Epoch 2/50
213/213 [==============================] - 824s 4s/step - loss: 3.3587 - accuracy: 0.0000e+00 - val_loss: 3.8668 - val_accuracy: 0.9977
Epoch 3/50
213/213 [==============================] - 826s 4s/step - loss: 3.3413 - accuracy: 0.0000e+00 - val_loss: 3.8510 - val_accuracy: 0.9977
Epoch 4/50
213/213 [==============================] - 824s 4s/step - loss: 3.3517 - accuracy: 0.0000e+00 - val_loss: 3.8375 - val_accuracy: 0.9977
Epoch 5/50
213/213 [==============================] - 826s 4s/step - loss: 3.3295 - accuracy: 0.0000e+00 - val_loss: 3.7210 - val_accuracy: 0.9978
Epoch 6/50
213/213 [==============================] - 825s 4s/step - loss: 3.3458 - accuracy: 0.0000e+00 - val_loss: 3.7927 - val_accuracy: 0.9978
Epoch 7/50
213/213 [==============================] - 826s 4s/step - loss: 3.3307 - accuracy: 0.0000e+00 - val_loss: 3

In [ ]:
model.save("/content/drive/My Drive/NER/model.h5")

In [ ]:
import numpy as np

id=np.random.randint(len(X_test))
print([idx2word[a] for a in X_test[id]])
predict=model.predict(X_test[id])
for i in range(max_len):
    if predict[i]==1:
        a=idx2word[X_test[id][i]]
        k=i+1
        while (k<len(X_test[id]) and predict[k]==2):
            a+=' '+idx2word[X_test[id][k]]
            k+=1
        print(a)

['nguy', 'hiểm', 'hơn', 'nữa', 'là', 'hacker', 'có', 'xu', 'hướng', 'sử', 'dụng', 'trí', 'tuệ', 'nhân', 'tạo', 'ai', 'để', 'tạo', 'nên', 'các', 'cuộc', 'tấn', 'công', 'mạng', 'quy', 'mô', 'và', 'chính', 'xác', 'hơn', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD', 'PAD',

In [ ]:
model_json = model.to_json()
with open("/content/drive/My Drive/NER/model.json", "w") as json_file:
    json_file.write(model_json)